/* Generated By:JavaCC: Do not edit this line. CreoleWikiScannerTokenManager.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.creole.javacc;
import org.wikimodel.wem.WikiStyle;
import org.wikimodel.wem.impl.IWikiScannerContext;
import org.wikimodel.wem.IWemConstants;

public class CreoleWikiScannerTokenManager implements CreoleWikiScannerConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(17, 0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 156;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 17:
                  if ((0x3ff0000ffffd9ffL & l) != 0L)
                  {
                     if (kind > 72)
                        kind = 72;
                     jjCheckNAdd(100);
                  }
                  else if ((0xfc00fffe00000000L & l) != 0L)
                  {
                     if (kind > 73)
                        kind = 73;
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 70)
                        kind = 70;
                     jjCheckNAddStates(0, 7);
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 71)
                        kind = 71;
                     jjCheckNAdd(99);
                  }
                  if (curChar == 13)
                     jjAddStates(8, 13);
                  else if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 40;
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 38;
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 36;
                  else if (curChar == 61)
                  {
                     if (kind > 65)
                        kind = 65;
                     jjstateSet[jjnewStateCnt++] = 27;
                  }
                  break;
               case 2:
               case 10:
                  jjCheckNAddStates(14, 19);
                  break;
               case 3:
                  if (curChar == 10)
                     jjCheckNAdd(9);
                  break;
               case 5:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAdd(9);
                  break;
               case 9:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 19:
               case 22:
                  jjCheckNAddStates(20, 23);
                  break;
               case 26:
                  if (curChar != 61)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 27:
                  if (curChar != 61)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAddStates(24, 27);
                  break;
               case 28:
                  if (curChar == 61 && kind > 65)
                     kind = 65;
                  break;
               case 29:
                  if (curChar != 61)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAdd(28);
                  break;
               case 30:
                  if (curChar != 61)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAddTwoStates(28, 29);
                  break;
               case 31:
                  if (curChar != 61)
                     break;
                  if (kind > 65)
                     kind = 65;
                  jjCheckNAddStates(28, 30);
                  break;
               case 33:
                  if (curChar == 61 && kind > 66)
                     kind = 66;
                  break;
               case 36:
                  if (curChar == 47 && kind > 68)
                     kind = 68;
                  break;
               case 37:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 38:
                  if (curChar == 42 && kind > 68)
                     kind = 68;
                  break;
               case 39:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 40:
                  if (curChar == 35 && kind > 68)
                     kind = 68;
                  break;
               case 41:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 43:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(43, 44);
                  break;
               case 44:
                  if (curChar == 58)
                     jjAddStates(31, 35);
                  break;
               case 46:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(46, 44);
                  break;
               case 47:
                  if (curChar != 47)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(36, 43);
                  break;
               case 48:
                  if ((0x2fff6fd200000000L & l) != 0L)
                     jjCheckNAddStates(44, 46);
                  break;
               case 49:
                  if (curChar == 37)
                     jjCheckNAdd(50);
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(44, 46);
                  break;
               case 53:
                  if (curChar == 37)
                     jjCheckNAdd(54);
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(47, 52);
                  break;
               case 56:
                  if ((0x2bff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(47, 52);
                  break;
               case 57:
                  if (curChar == 58)
                     jjCheckNAdd(58);
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(53, 56);
                  break;
               case 59:
                  if (curChar != 47)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(57, 61);
                  break;
               case 60:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(57, 61);
                  break;
               case 61:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(57, 61);
                  break;
               case 64:
                  if (curChar != 63)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(62, 64);
                  break;
               case 65:
                  if ((0xafffefd200000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(62, 64);
                  break;
               case 66:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(62, 64);
                  break;
               case 69:
                  if (curChar != 35)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddTwoStates(70, 71);
                  break;
               case 70:
                  if ((0xafffefd200000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddTwoStates(70, 71);
                  break;
               case 71:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 72:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddTwoStates(70, 71);
                  break;
               case 74:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(50, 54);
                  break;
               case 75:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 76:
                  if (curChar != 47)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(65, 68);
                  break;
               case 77:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(69, 73);
                  break;
               case 78:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(69, 73);
                  break;
               case 81:
                  if (curChar != 47)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(74, 78);
                  break;
               case 82:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(74, 78);
                  break;
               case 83:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 84:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(74, 78);
                  break;
               case 86:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 87:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(89, 92);
                  break;
               case 89:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 91:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(79, 83);
                  break;
               case 92:
                  if ((0x2bff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(79, 83);
                  break;
               case 93:
                  if (curChar != 47)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(84, 88);
                  break;
               case 94:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(84, 88);
                  break;
               case 95:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 96;
                  break;
               case 96:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 97:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(84, 88);
                  break;
               case 98:
                  if ((0x2bff6fd200000000L & l) != 0L)
                     jjCheckNAddTwoStates(89, 92);
                  break;
               case 99:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 71)
                     kind = 71;
                  jjCheckNAdd(99);
                  break;
               case 100:
                  if ((0x3ff0000ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 72)
                     kind = 72;
                  jjCheckNAdd(100);
                  break;
               case 101:
                  if ((0xfc00fffe00000000L & l) != 0L && kind > 73)
                     kind = 73;
                  break;
               case 102:
                  if (curChar == 13)
                     jjAddStates(8, 13);
                  break;
               case 103:
                  if (curChar == 10)
                     jjCheckNAddStates(89, 92);
                  break;
               case 104:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(104, 105);
                  break;
               case 105:
                  if ((0xc00040800000000L & l) != 0L)
                     jjCheckNAdd(106);
                  break;
               case 106:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(106);
                  break;
               case 107:
                  if ((0x40800000000L & l) != 0L)
                     jjAddStates(93, 94);
                  break;
               case 108:
                  if ((0xc00040800000000L & l) != 0L)
                     jjCheckNAdd(109);
                  break;
               case 109:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(109);
                  break;
               case 110:
                  if ((0xc00040800000000L & l) != 0L)
                     jjCheckNAdd(111);
                  break;
               case 111:
                  if ((0xc00040800000000L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAddTwoStates(111, 112);
                  break;
               case 112:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(112);
                  break;
               case 113:
                  if ((0xc00000000000000L & l) != 0L)
                     jjAddStates(95, 96);
                  break;
               case 114:
                  if ((0x40800000000L & l) != 0L)
                     jjCheckNAdd(115);
                  break;
               case 115:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(115);
                  break;
               case 116:
                  if ((0x40800000000L & l) != 0L)
                     jjCheckNAdd(117);
                  break;
               case 117:
                  if ((0xc00040800000000L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAddTwoStates(117, 118);
                  break;
               case 118:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(118);
                  break;
               case 119:
                  if (curChar == 10)
                     jjCheckNAdd(120);
                  break;
               case 121:
                  if (curChar == 61 && kind > 59)
                     kind = 59;
                  break;
               case 122:
                  if (curChar == 10)
                     jjCheckNAdd(123);
                  break;
               case 123:
                  if (curChar != 61)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAddTwoStates(124, 125);
                  break;
               case 124:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(124);
                  break;
               case 125:
                  if (curChar != 61)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAddStates(97, 101);
                  break;
               case 126:
                  if (curChar != 61)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(124);
                  break;
               case 127:
                  if (curChar != 61)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAddTwoStates(126, 124);
                  break;
               case 128:
                  if (curChar != 61)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAddStates(102, 104);
                  break;
               case 129:
                  if (curChar != 61)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAddStates(105, 108);
                  break;
               case 130:
                  if (curChar == 10)
                     jjCheckNAdd(148);
                  break;
               case 133:
               case 141:
                  jjCheckNAddStates(109, 114);
                  break;
               case 134:
                  if (curChar == 10)
                     jjCheckNAdd(140);
                  break;
               case 136:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 137:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAdd(140);
                  break;
               case 140:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 149:
                  if (curChar == 10)
                     jjCheckNAdd(153);
                  break;
               case 150:
                  if (curChar == 45)
                     jjCheckNAdd(151);
                  break;
               case 151:
                  if (curChar != 45)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjCheckNAdd(151);
                  break;
               case 152:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 153:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 154:
                  if (curChar == 10 && kind > 70)
                     kind = 70;
                  break;
               case 155:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 70)
                     kind = 70;
                  jjCheckNAddStates(0, 7);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 17:
                  if ((0x87fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 72)
                        kind = 72;
                     jjCheckNAdd(100);
                  }
                  else if ((0x78000001f8000001L & l) != 0L)
                  {
                     if (kind > 73)
                        kind = 73;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(43, 44);
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 34;
                  else if (curChar == 124)
                  {
                     if (kind > 66)
                        kind = 66;
                     jjstateSet[jjnewStateCnt++] = 33;
                  }
                  else if (curChar == 91)
                     jjstateSet[jjnewStateCnt++] = 18;
                  else if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 0:
                  if (curChar == 123)
                     jjCheckNAddStates(14, 19);
                  break;
               case 1:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  jjCheckNAddStates(14, 19);
                  break;
               case 4:
                  if (curChar == 125)
                     jjCheckNAddStates(14, 19);
                  break;
               case 7:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 8:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 10:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(14, 19);
                  break;
               case 11:
               case 13:
                  if (curChar == 125)
                     jjCheckNAdd(10);
                  break;
               case 12:
                  if (curChar == 125)
                     jjAddStates(115, 116);
                  break;
               case 14:
                  if (curChar == 125 && kind > 63)
                     kind = 63;
                  break;
               case 15:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 18:
                  if (curChar == 91)
                     jjCheckNAddStates(20, 23);
                  break;
               case 19:
                  if ((0xffffffffdfffffffL & l) != 0L)
                     jjCheckNAddStates(20, 23);
                  break;
               case 20:
                  if (curChar == 93)
                     jjCheckNAdd(19);
                  break;
               case 21:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 22:
                  jjCheckNAddStates(20, 23);
                  break;
               case 23:
                  if (curChar == 93 && kind > 64)
                     kind = 64;
                  break;
               case 24:
                  if (curChar == 93)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 91)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 32:
                  if (curChar != 124)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 34:
                  if (curChar == 92 && kind > 67)
                     kind = 67;
                  break;
               case 35:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 42:
               case 43:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(43, 44);
                  break;
               case 45:
               case 46:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(46, 44);
                  break;
               case 48:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(44, 46);
                  break;
               case 50:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(44, 46);
                  break;
               case 52:
                  if (curChar != 64)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(47, 52);
                  break;
               case 54:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(47, 52);
                  break;
               case 56:
                  if ((0x47fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(47, 52);
                  break;
               case 60:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(57, 61);
                  break;
               case 62:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(57, 61);
                  break;
               case 65:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(62, 64);
                  break;
               case 67:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(62, 64);
                  break;
               case 70:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddTwoStates(70, 71);
                  break;
               case 72:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddTwoStates(70, 71);
                  break;
               case 77:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(69, 73);
                  break;
               case 79:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(69, 73);
                  break;
               case 82:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(74, 78);
                  break;
               case 84:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(74, 78);
                  break;
               case 87:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 88:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(89, 92);
                  break;
               case 90:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 91;
                  break;
               case 91:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(79, 83);
                  break;
               case 92:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(79, 83);
                  break;
               case 94:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(84, 88);
                  break;
               case 96:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 97:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAddStates(84, 88);
                  break;
               case 98:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(89, 92);
                  break;
               case 100:
                  if ((0x87fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 72)
                     kind = 72;
                  jjCheckNAdd(100);
                  break;
               case 101:
                  if ((0x78000001f8000001L & l) != 0L && kind > 73)
                     kind = 73;
                  break;
               case 120:
                  if (curChar != 124)
                     break;
                  if (kind > 59)
                     kind = 59;
                  jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 131:
                  if (curChar == 123)
                     jjCheckNAddStates(109, 114);
                  break;
               case 132:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 133:
                  jjCheckNAddStates(109, 114);
                  break;
               case 135:
                  if (curChar == 125)
                     jjCheckNAddStates(109, 114);
                  break;
               case 138:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 139:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 141:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(109, 114);
                  break;
               case 142:
               case 144:
                  if (curChar == 125)
                     jjCheckNAdd(141);
                  break;
               case 143:
                  if (curChar == 125)
                     jjAddStates(117, 118);
                  break;
               case 145:
                  if (curChar == 125 && kind > 61)
                     kind = 61;
                  break;
               case 146:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 145;
                  break;
               case 147:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 131;
                  break;
               case 148:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 17:
               case 100:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 72)
                     kind = 72;
                  jjCheckNAdd(100);
                  break;
               case 2:
               case 10:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(14, 19);
                  break;
               case 19:
               case 22:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(20, 23);
                  break;
               case 133:
               case 141:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(109, 114);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 156 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjMoveStringLiteralDfa0_1()
{
   return jjMoveNfa_1(13, 0);
}
private final int jjMoveNfa_1(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 157;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 13:
                  if ((0x3ff0000ffffd9ffL & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     jjCheckNAdd(79);
                  }
                  else if ((0xfc00fffe00000000L & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 55)
                        kind = 55;
                     jjCheckNAddStates(119, 121);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 54)
                        kind = 54;
                     jjCheckNAddStates(122, 129);
                  }
                  if ((0xc00040800000000L & l) != 0L)
                     jjCheckNAdd(1);
                  else if (curChar == 61)
                  {
                     if (kind > 44)
                        kind = 44;
                     jjCheckNAddStates(130, 132);
                  }
                  else if (curChar == 13)
                     jjAddStates(133, 138);
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 16;
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 4;
                  if ((0xc00000000000000L & l) != 0L)
                     jjAddStates(139, 140);
                  else if ((0x40800000000L & l) != 0L)
                     jjAddStates(141, 142);
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 20;
                  else if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 0:
                  if ((0xc00040800000000L & l) != 0L)
                     jjCheckNAdd(1);
                  break;
               case 1:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if (curChar == 45)
                     jjCheckNAdd(3);
                  break;
               case 3:
                  if (curChar != 45)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(3);
                  break;
               case 4:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 5:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 7:
               case 10:
                  jjCheckNAddStates(143, 146);
                  break;
               case 16:
                  if (curChar == 47 && kind > 52)
                     kind = 52;
                  break;
               case 17:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 18:
                  if (curChar == 42 && kind > 52)
                     kind = 52;
                  break;
               case 19:
                  if (curChar == 42)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 35 && kind > 52)
                     kind = 52;
                  break;
               case 21:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 23:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 24:
                  if (curChar == 58)
                     jjAddStates(147, 151);
                  break;
               case 26:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(26, 24);
                  break;
               case 27:
                  if (curChar != 47)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(152, 159);
                  break;
               case 28:
                  if ((0x2fff6fd200000000L & l) != 0L)
                     jjCheckNAddStates(160, 162);
                  break;
               case 29:
                  if (curChar == 37)
                     jjCheckNAdd(30);
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(160, 162);
                  break;
               case 33:
                  if (curChar == 37)
                     jjCheckNAdd(34);
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(163, 168);
                  break;
               case 36:
                  if ((0x2bff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(163, 168);
                  break;
               case 37:
                  if (curChar == 58)
                     jjCheckNAdd(38);
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(169, 172);
                  break;
               case 39:
                  if (curChar != 47)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(173, 177);
                  break;
               case 40:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(173, 177);
                  break;
               case 41:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(173, 177);
                  break;
               case 44:
                  if (curChar != 63)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(178, 180);
                  break;
               case 45:
                  if ((0xafffefd200000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(178, 180);
                  break;
               case 46:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(178, 180);
                  break;
               case 49:
                  if (curChar != 35)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(50, 51);
                  break;
               case 50:
                  if ((0xafffefd200000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(50, 51);
                  break;
               case 51:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(50, 51);
                  break;
               case 54:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(30, 34);
                  break;
               case 55:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 56:
                  if (curChar != 47)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(181, 184);
                  break;
               case 57:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(185, 189);
                  break;
               case 58:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(185, 189);
                  break;
               case 61:
                  if (curChar != 47)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(190, 194);
                  break;
               case 62:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(190, 194);
                  break;
               case 63:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(190, 194);
                  break;
               case 66:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(69, 72);
                  break;
               case 69:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(195, 199);
                  break;
               case 72:
                  if ((0x2bff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(195, 199);
                  break;
               case 73:
                  if (curChar != 47)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(200, 204);
                  break;
               case 74:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(200, 204);
                  break;
               case 75:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(200, 204);
                  break;
               case 78:
                  if ((0x2bff6fd200000000L & l) != 0L)
                     jjCheckNAddTwoStates(69, 72);
                  break;
               case 79:
                  if ((0x3ff0000ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAdd(79);
                  break;
               case 80:
                  if ((0xfc00fffe00000000L & l) != 0L && kind > 57)
                     kind = 57;
                  break;
               case 81:
                  if ((0x40800000000L & l) != 0L)
                     jjAddStates(141, 142);
                  break;
               case 82:
                  if ((0xc00040800000000L & l) != 0L)
                     jjCheckNAdd(83);
                  break;
               case 83:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAdd(83);
                  break;
               case 84:
                  if ((0xc00040800000000L & l) != 0L)
                     jjCheckNAdd(85);
                  break;
               case 85:
                  if ((0xc00040800000000L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddTwoStates(85, 86);
                  break;
               case 86:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAdd(86);
                  break;
               case 87:
                  if ((0xc00000000000000L & l) != 0L)
                     jjAddStates(139, 140);
                  break;
               case 88:
                  if ((0x40800000000L & l) != 0L)
                     jjCheckNAdd(89);
                  break;
               case 89:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAdd(89);
                  break;
               case 90:
                  if ((0x40800000000L & l) != 0L)
                     jjCheckNAdd(91);
                  break;
               case 91:
                  if ((0xc00040800000000L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAddTwoStates(91, 92);
                  break;
               case 92:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 42)
                     kind = 42;
                  jjCheckNAdd(92);
                  break;
               case 93:
                  if (curChar == 13)
                     jjAddStates(133, 138);
                  break;
               case 94:
                  if (curChar == 10)
                     jjCheckNAddStates(205, 208);
                  break;
               case 95:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(95, 0);
                  break;
               case 96:
                  if (curChar == 10)
                     jjCheckNAdd(97);
                  break;
               case 98:
                  if (curChar == 61 && kind > 43)
                     kind = 43;
                  break;
               case 99:
                  if (curChar == 10)
                     jjCheckNAdd(100);
                  break;
               case 100:
                  if (curChar != 61)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddTwoStates(101, 102);
                  break;
               case 101:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAdd(101);
                  break;
               case 102:
                  if (curChar != 61)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddStates(209, 213);
                  break;
               case 103:
                  if (curChar != 61)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAdd(101);
                  break;
               case 104:
                  if (curChar != 61)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddTwoStates(103, 101);
                  break;
               case 105:
                  if (curChar != 61)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddStates(214, 216);
                  break;
               case 106:
                  if (curChar != 61)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddStates(217, 220);
                  break;
               case 107:
                  if (curChar == 10)
                     jjCheckNAdd(125);
                  break;
               case 110:
               case 118:
                  jjCheckNAddStates(221, 226);
                  break;
               case 111:
                  if (curChar == 10)
                     jjCheckNAdd(117);
                  break;
               case 113:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 114:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAdd(117);
                  break;
               case 117:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 126:
                  if (curChar == 10)
                     jjCheckNAdd(5);
                  break;
               case 127:
                  if (curChar == 10 && kind > 54)
                     kind = 54;
                  break;
               case 128:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 54)
                     kind = 54;
                  jjCheckNAddStates(122, 129);
                  break;
               case 129:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAddStates(119, 121);
                  break;
               case 130:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAdd(130);
                  break;
               case 132:
                  if (curChar == 61 && kind > 50)
                     kind = 50;
                  break;
               case 133:
                  if (curChar != 61)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAddStates(130, 132);
                  break;
               case 134:
                  if (curChar != 61)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAddStates(227, 230);
                  break;
               case 135:
                  if (curChar == 61 && kind > 49)
                     kind = 49;
                  break;
               case 136:
                  if (curChar != 61)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(135);
                  break;
               case 137:
                  if (curChar != 61)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAddTwoStates(135, 136);
                  break;
               case 138:
                  if (curChar != 61)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAddStates(231, 233);
                  break;
               case 142:
               case 150:
                  jjCheckNAddStates(234, 239);
                  break;
               case 143:
                  if (curChar == 10)
                     jjCheckNAdd(149);
                  break;
               case 145:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 146:
                  if ((0x2400L & l) != 0L)
                     jjCheckNAdd(149);
                  break;
               case 149:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 13:
                  if ((0x87fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     jjCheckNAdd(79);
                  }
                  else if ((0x78000001f8000001L & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  else if (curChar == 123)
                     jjCheckNAddTwoStates(124, 156);
                  else if (curChar == 124)
                  {
                     if (kind > 43)
                        kind = 43;
                     jjCheckNAddTwoStates(98, 132);
                  }
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 14;
                  else if (curChar == 91)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if (curChar == 91)
                     jjCheckNAddStates(143, 146);
                  break;
               case 7:
                  if ((0xffffffffdfffffffL & l) != 0L)
                     jjCheckNAddStates(143, 146);
                  break;
               case 8:
                  if (curChar == 93)
                     jjCheckNAdd(7);
                  break;
               case 9:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  jjCheckNAddStates(143, 146);
                  break;
               case 11:
                  if (curChar == 93 && kind > 48)
                     kind = 48;
                  break;
               case 12:
                  if (curChar == 93)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 14:
                  if (curChar == 92 && kind > 51)
                     kind = 51;
                  break;
               case 15:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 22:
               case 23:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(23, 24);
                  break;
               case 25:
               case 26:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(26, 24);
                  break;
               case 28:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(160, 162);
                  break;
               case 30:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 31;
                  break;
               case 31:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(160, 162);
                  break;
               case 32:
                  if (curChar != 64)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(163, 168);
                  break;
               case 34:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(163, 168);
                  break;
               case 36:
                  if ((0x47fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(163, 168);
                  break;
               case 40:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(173, 177);
                  break;
               case 42:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(173, 177);
                  break;
               case 45:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(178, 180);
                  break;
               case 47:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(178, 180);
                  break;
               case 50:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(50, 51);
                  break;
               case 52:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddTwoStates(50, 51);
                  break;
               case 57:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(185, 189);
                  break;
               case 59:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 60:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(185, 189);
                  break;
               case 62:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(190, 194);
                  break;
               case 64:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(190, 194);
                  break;
               case 67:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(69, 72);
                  break;
               case 70:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(195, 199);
                  break;
               case 72:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(195, 199);
                  break;
               case 74:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(200, 204);
                  break;
               case 76:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjCheckNAddStates(200, 204);
                  break;
               case 78:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(69, 72);
                  break;
               case 79:
                  if ((0x87fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAdd(79);
                  break;
               case 80:
                  if ((0x78000001f8000001L & l) != 0L && kind > 57)
                     kind = 57;
                  break;
               case 97:
                  if (curChar != 124)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAdd(98);
                  break;
               case 108:
                  if (curChar == 123)
                     jjCheckNAddStates(221, 226);
                  break;
               case 109:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 110:
                  jjCheckNAddStates(221, 226);
                  break;
               case 112:
                  if (curChar == 125)
                     jjCheckNAddStates(221, 226);
                  break;
               case 115:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 116:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 118:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(221, 226);
                  break;
               case 119:
               case 121:
                  if (curChar == 125)
                     jjCheckNAdd(118);
                  break;
               case 120:
                  if (curChar == 125)
                     jjAddStates(240, 241);
                  break;
               case 122:
                  if (curChar == 125 && kind > 45)
                     kind = 45;
                  break;
               case 123:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 124:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 125:
                  if (curChar == 123)
                     jjCheckNAdd(124);
                  break;
               case 131:
                  if (curChar != 124)
                     break;
                  if (kind > 43)
                     kind = 43;
                  jjCheckNAddTwoStates(98, 132);
                  break;
               case 139:
                  if (curChar == 123)
                     jjCheckNAddTwoStates(124, 156);
                  break;
               case 140:
                  if (curChar == 123)
                     jjCheckNAddStates(234, 239);
                  break;
               case 141:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 142:
                  jjCheckNAddStates(234, 239);
                  break;
               case 144:
                  if (curChar == 125)
                     jjCheckNAddStates(234, 239);
                  break;
               case 147:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 148:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 150:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(234, 239);
                  break;
               case 151:
               case 153:
                  if (curChar == 125)
                     jjCheckNAdd(150);
                  break;
               case 152:
                  if (curChar == 125)
                     jjAddStates(242, 243);
                  break;
               case 154:
                  if (curChar == 125 && kind > 47)
                     kind = 47;
                  break;
               case 155:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 140;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 13:
               case 79:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAdd(79);
                  break;
               case 7:
               case 10:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(143, 146);
                  break;
               case 110:
               case 118:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(221, 226);
                  break;
               case 142:
               case 150:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(234, 239);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 157 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   104, 105, 120, 123, 148, 153, 107, 113, 103, 119, 122, 130, 149, 154, 1, 5, 
   6, 10, 11, 12, 19, 20, 21, 24, 28, 29, 30, 31, 28, 29, 30, 45, 
   75, 76, 86, 98, 48, 52, 56, 57, 59, 64, 69, 74, 49, 48, 52, 53, 
   56, 57, 59, 64, 69, 58, 59, 64, 69, 59, 60, 61, 64, 69, 65, 66, 
   69, 77, 78, 64, 69, 77, 78, 81, 64, 69, 81, 82, 83, 64, 69, 89, 
   92, 93, 64, 69, 93, 94, 95, 64, 69, 104, 105, 107, 113, 108, 110, 114, 
   116, 126, 124, 127, 128, 129, 126, 124, 127, 126, 124, 127, 128, 132, 136, 137, 
   141, 142, 143, 13, 15, 144, 146, 95, 0, 130, 95, 0, 97, 100, 125, 5, 
   81, 87, 101, 134, 102, 94, 96, 99, 107, 126, 127, 88, 90, 82, 84, 7, 
   8, 9, 12, 25, 55, 56, 66, 78, 28, 32, 36, 37, 39, 44, 49, 54, 
   29, 28, 32, 33, 36, 37, 39, 44, 49, 38, 39, 44, 49, 39, 40, 41, 
   44, 49, 45, 46, 49, 57, 58, 44, 49, 57, 58, 61, 44, 49, 61, 62, 
   63, 44, 49, 69, 72, 73, 44, 49, 73, 74, 75, 44, 49, 95, 0, 81, 
   87, 103, 101, 104, 105, 106, 103, 101, 104, 103, 101, 104, 105, 109, 113, 114, 
   118, 119, 120, 135, 136, 137, 138, 135, 136, 137, 141, 145, 146, 150, 151, 152, 
   121, 123, 153, 155, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
   "INITIAL_CONTEXT", 
};
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[157];
private final int[] jjstateSet = new int[314];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
public CreoleWikiScannerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public CreoleWikiScannerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 157; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   if (jjmatchedPos < 0)
   {
      if (image == null)
         t.image = "";
      else
         t.image = image.toString();
      t.beginLine = t.endLine = input_stream.getBeginLine();
      t.beginColumn = t.endColumn = input_stream.getBeginColumn();
   }
   else
   {
      String im = jjstrLiteralImages[jjmatchedKind];
      t.image = (im == null) ? input_stream.GetImage() : im;
      t.beginLine = input_stream.getBeginLine();
      t.beginColumn = input_stream.getBeginColumn();
      t.endLine = input_stream.getEndLine();
      t.endColumn = input_stream.getEndColumn();
   }
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 54;
       jjmatchedPos = -1;
       curPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default : 
         break;
   }
}
}
