/* Generated By:JavaCC: Do not edit this line. CreoleWikiScannerConstants.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.creole.javacc;

public interface CreoleWikiScannerConstants {

  int EOF = 0;
  int LI = 1;
  int DL = 2;
  int LIST_ITEM = 3;
  int HEADER = 4;
  int VERBATIM = 5;
  int REFERENCE = 6;
  int HORLINE = 7;
  int BR = 8;
  int CELL = 9;
  int FORMAT_SYMBOL = 10;
  int NEW_LINE = 11;
  int SPACE = 12;
  int SPECIAL_SYMBOL = 13;
  int CHAR = 14;
  int URI = 15;
  int ALPHA = 16;
  int DIGIT = 17;
  int HEXDIG = 18;
  int URI_GEN_DELIMS = 19;
  int URI_SUB_DELIMS = 20;
  int URI_UNRESERVED = 21;
  int URI_RESERVED = 22;
  int URI_SCHEME = 23;
  int URI_SCHEME_COMPOSITE = 24;
  int URI_PCT_ENCODED = 25;
  int URI_PCHAR_FIRST = 26;
  int URI_PCHAR = 27;
  int URI_QUERY = 28;
  int URI_FRAGMENT = 29;
  int URI_HIER_PART = 30;
  int URI_AUTHORITY = 31;
  int URI_USERINFO = 32;
  int URI_PATH_ABEMPTY = 33;
  int URI_PATH_ABSOLUTE = 34;
  int URI_PATH_ROOTLESS = 35;
  int URI_SEGMENT = 36;
  int URI_SEGMENT_NZ = 37;
  int URI_SEGMENT_NZ_NC = 38;
  int URI_PORT = 39;
  int URI_HOST = 40;
  int URI_REG_NAME = 41;
  int I_LIST_ITEM = 42;
  int I_TABLE_ROW = 43;
  int I_HEADER_BEGIN = 44;
  int I_VERBATIM_BLOCK = 45;
  int I_HORLINE = 46;
  int I_VERBATIM_INLINE = 47;
  int I_REFERENCE = 48;
  int I_HEADER_END = 49;
  int I_TABLE_CELL = 50;
  int I_BR = 51;
  int I_FORMAT_SYMBOL = 52;
  int I_URI = 53;
  int I_NL = 54;
  int I_SPACE = 55;
  int I_WORD = 56;
  int I_SPECIAL_SYMBOL = 57;
  int D_LIST_ITEM = 58;
  int D_TABLE_ROW = 59;
  int D_HEADER_BEGIN = 60;
  int D_VERBATIM_BLOCK = 61;
  int D_HORLINE = 62;
  int D_VERBATIM_INLINE = 63;
  int D_REFERENCE = 64;
  int D_HEADER_END = 65;
  int D_TABLE_CELL = 66;
  int D_BR = 67;
  int D_FORMAT_SYMBOL = 68;
  int D_URI = 69;
  int D_NL = 70;
  int D_SPACE = 71;
  int D_WORD = 72;
  int D_SPECIAL_SYMBOL = 73;

  int DEFAULT = 0;
  int INITIAL_CONTEXT = 1;

  String[] tokenImage = {
    "<EOF>",
    "<LI>",
    "<DL>",
    "<LIST_ITEM>",
    "<HEADER>",
    "<VERBATIM>",
    "<REFERENCE>",
    "<HORLINE>",
    "\"\\\\\\\\\"",
    "<CELL>",
    "<FORMAT_SYMBOL>",
    "<NEW_LINE>",
    "<SPACE>",
    "<SPECIAL_SYMBOL>",
    "<CHAR>",
    "<URI>",
    "<ALPHA>",
    "<DIGIT>",
    "<HEXDIG>",
    "<URI_GEN_DELIMS>",
    "<URI_SUB_DELIMS>",
    "<URI_UNRESERVED>",
    "<URI_RESERVED>",
    "<URI_SCHEME>",
    "<URI_SCHEME_COMPOSITE>",
    "<URI_PCT_ENCODED>",
    "<URI_PCHAR_FIRST>",
    "<URI_PCHAR>",
    "<URI_QUERY>",
    "<URI_FRAGMENT>",
    "<URI_HIER_PART>",
    "<URI_AUTHORITY>",
    "<URI_USERINFO>",
    "<URI_PATH_ABEMPTY>",
    "<URI_PATH_ABSOLUTE>",
    "<URI_PATH_ROOTLESS>",
    "<URI_SEGMENT>",
    "<URI_SEGMENT_NZ>",
    "<URI_SEGMENT_NZ_NC>",
    "<URI_PORT>",
    "<URI_HOST>",
    "<URI_REG_NAME>",
    "<I_LIST_ITEM>",
    "<I_TABLE_ROW>",
    "<I_HEADER_BEGIN>",
    "<I_VERBATIM_BLOCK>",
    "<I_HORLINE>",
    "<I_VERBATIM_INLINE>",
    "<I_REFERENCE>",
    "<I_HEADER_END>",
    "<I_TABLE_CELL>",
    "<I_BR>",
    "<I_FORMAT_SYMBOL>",
    "<I_URI>",
    "<I_NL>",
    "<I_SPACE>",
    "<I_WORD>",
    "<I_SPECIAL_SYMBOL>",
    "<D_LIST_ITEM>",
    "<D_TABLE_ROW>",
    "<D_HEADER_BEGIN>",
    "<D_VERBATIM_BLOCK>",
    "<D_HORLINE>",
    "<D_VERBATIM_INLINE>",
    "<D_REFERENCE>",
    "<D_HEADER_END>",
    "<D_TABLE_CELL>",
    "<D_BR>",
    "<D_FORMAT_SYMBOL>",
    "<D_URI>",
    "<D_NL>",
    "<D_SPACE>",
    "<D_WORD>",
    "<D_SPECIAL_SYMBOL>",
  };

}
