/* Generated By:JavaCC: Do not edit this line. JspWikiScannerTokenManager.java */
/*******************************************************************************
 * Copyright (c) 2005,2007 Cognium Systems SA and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Apache License, Version 2.0
 * which accompanies this distribution, and is available at
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Contributors:
 *     Cognium Systems SA - initial API and implementation
 *******************************************************************************/
package org.wikimodel.wem.jspwiki.javacc;
import org.wikimodel.wem.WikiStyle;
import org.wikimodel.wem.impl.IWikiScannerContext;

public class JspWikiScannerTokenManager implements JspWikiScannerConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjMoveStringLiteralDfa0_0()
{
   return jjMoveNfa_0(1, 0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 123;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff0000ffffd9ffL & l) != 0L)
                  {
                     if (kind > 76)
                        kind = 76;
                     jjCheckNAdd(85);
                  }
                  else if ((0xfc00fffe00000000L & l) != 0L)
                  {
                     if (kind > 77)
                        kind = 77;
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 75)
                        kind = 75;
                     jjCheckNAddStates(0, 2);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 74)
                        kind = 74;
                     jjCheckNAddStates(3, 9);
                  }
                  if (curChar == 13)
                     jjAddStates(10, 15);
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 22;
                  else if (curChar == 58)
                  {
                     if (kind > 69)
                        kind = 69;
                     jjCheckNAdd(13);
                  }
                  break;
               case 3:
                  if ((0xfffffffeffffd9ffL & l) != 0L && kind > 61)
                     kind = 61;
                  break;
               case 6:
               case 7:
                  jjCheckNAddStates(16, 18);
                  break;
               case 12:
                  if (curChar != 58)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAdd(13);
                  break;
               case 13:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 69)
                     kind = 69;
                  jjCheckNAdd(13);
                  break;
               case 16:
               case 17:
                  jjCheckNAddStates(19, 22);
                  break;
               case 22:
                  if (curChar == 39 && kind > 71)
                     kind = 71;
                  break;
               case 23:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 29:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(29, 30);
                  break;
               case 30:
                  if (curChar == 58)
                     jjAddStates(23, 27);
                  break;
               case 32:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(32, 30);
                  break;
               case 33:
                  if (curChar != 47)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(28, 35);
                  break;
               case 34:
                  if ((0x2fff6fd200000000L & l) != 0L)
                     jjCheckNAddStates(36, 38);
                  break;
               case 35:
                  if (curChar == 37)
                     jjCheckNAdd(36);
                  break;
               case 36:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(36, 38);
                  break;
               case 39:
                  if (curChar == 37)
                     jjCheckNAdd(40);
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(39, 44);
                  break;
               case 42:
                  if ((0x2bff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(39, 44);
                  break;
               case 43:
                  if (curChar == 58)
                     jjCheckNAdd(44);
                  break;
               case 44:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(45, 48);
                  break;
               case 45:
                  if (curChar != 47)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(49, 53);
                  break;
               case 46:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(49, 53);
                  break;
               case 47:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(49, 53);
                  break;
               case 50:
                  if (curChar != 63)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(54, 56);
                  break;
               case 51:
                  if ((0xafffefd200000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(54, 56);
                  break;
               case 52:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(54, 56);
                  break;
               case 55:
                  if (curChar != 35)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddTwoStates(56, 57);
                  break;
               case 56:
                  if ((0xafffefd200000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddTwoStates(56, 57);
                  break;
               case 57:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddTwoStates(56, 57);
                  break;
               case 60:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(36, 40);
                  break;
               case 61:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 62:
                  if (curChar != 47)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(57, 60);
                  break;
               case 63:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(61, 65);
                  break;
               case 64:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(61, 65);
                  break;
               case 67:
                  if (curChar != 47)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(66, 70);
                  break;
               case 68:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(66, 70);
                  break;
               case 69:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(66, 70);
                  break;
               case 72:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(75, 78);
                  break;
               case 75:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(71, 75);
                  break;
               case 78:
                  if ((0x2bff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(71, 75);
                  break;
               case 79:
                  if (curChar != 47)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(76, 80);
                  break;
               case 80:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(76, 80);
                  break;
               case 81:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 83:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(76, 80);
                  break;
               case 84:
                  if ((0x2bff6fd200000000L & l) != 0L)
                     jjCheckNAddTwoStates(75, 78);
                  break;
               case 85:
                  if ((0x3ff0000ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(85);
                  break;
               case 86:
                  if ((0xfc00fffe00000000L & l) != 0L && kind > 77)
                     kind = 77;
                  break;
               case 87:
                  if (curChar == 13)
                     jjAddStates(10, 15);
                  break;
               case 88:
                  if (curChar == 10)
                     jjCheckNAdd(89);
                  break;
               case 89:
                  if ((0xc00040800000000L & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjCheckNAddTwoStates(89, 90);
                  break;
               case 90:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  jjCheckNAdd(90);
                  break;
               case 91:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(93, 94);
                  break;
               case 95:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(96, 98);
                  break;
               case 96:
               case 99:
                  if (curChar != 33)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjCheckNAdd(97);
                  break;
               case 97:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjCheckNAdd(97);
                  break;
               case 98:
                  if (curChar == 33)
                     jjCheckNAddTwoStates(100, 99);
                  break;
               case 100:
                  if (curChar == 33)
                     jjCheckNAdd(99);
                  break;
               case 101:
                  if (curChar == 10)
                     jjCheckNAdd(112);
                  break;
               case 104:
               case 105:
                  jjCheckNAddStates(81, 84);
                  break;
               case 113:
                  if (curChar == 10)
                     jjCheckNAdd(117);
                  break;
               case 114:
                  if (curChar == 45)
                     jjCheckNAdd(115);
                  break;
               case 115:
                  if (curChar != 45)
                     break;
                  if (kind > 66)
                     kind = 66;
                  jjCheckNAdd(115);
                  break;
               case 116:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 117:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 118:
                  if (curChar == 10 && kind > 74)
                     kind = 74;
                  break;
               case 119:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 74)
                     kind = 74;
                  jjCheckNAddStates(3, 9);
                  break;
               case 120:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAddStates(0, 2);
                  break;
               case 121:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(121, 12);
                  break;
               case 122:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 75)
                     kind = 75;
                  jjCheckNAdd(122);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x87fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 76)
                        kind = 76;
                     jjCheckNAdd(85);
                  }
                  else if ((0x78000001f8000001L & l) != 0L)
                  {
                     if (kind > 77)
                        kind = 77;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(29, 30);
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 26;
                  else if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 24;
                  else if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 14;
                  else if (curChar == 124)
                  {
                     if (kind > 68)
                        kind = 68;
                  }
                  else if (curChar == 91)
                     jjCheckNAddStates(16, 18);
                  else if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 3;
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 9;
                  else if (curChar == 91)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 0:
                  if (curChar == 91 && kind > 61)
                     kind = 61;
                  break;
               case 2:
                  if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if (kind > 61)
                     kind = 61;
                  break;
               case 4:
                  if (curChar == 91)
                     jjCheckNAddStates(16, 18);
                  break;
               case 5:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  jjCheckNAddStates(16, 18);
                  break;
               case 7:
                  if ((0xffffffffd7ffffffL & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 8:
                  if (curChar == 93 && kind > 67)
                     kind = 67;
                  break;
               case 9:
                  if (curChar == 124 && kind > 68)
                     kind = 68;
                  break;
               case 10:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 124 && kind > 68)
                     kind = 68;
                  break;
               case 14:
                  if (curChar == 123)
                     jjCheckNAddStates(19, 22);
                  break;
               case 15:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 16:
                  jjCheckNAddStates(19, 22);
                  break;
               case 17:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(19, 22);
                  break;
               case 18:
                  if (curChar == 125)
                     jjCheckNAdd(17);
                  break;
               case 19:
                  if (curChar == 125 && kind > 70)
                     kind = 70;
                  break;
               case 20:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 24:
                  if (curChar == 95 && kind > 71)
                     kind = 71;
                  break;
               case 25:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 92 && kind > 72)
                     kind = 72;
                  break;
               case 27:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
               case 29:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(29, 30);
                  break;
               case 31:
               case 32:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(32, 30);
                  break;
               case 34:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(36, 38);
                  break;
               case 36:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 37;
                  break;
               case 37:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(36, 38);
                  break;
               case 38:
                  if (curChar != 64)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(39, 44);
                  break;
               case 40:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 41:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(39, 44);
                  break;
               case 42:
                  if ((0x47fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(39, 44);
                  break;
               case 46:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(49, 53);
                  break;
               case 48:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(49, 53);
                  break;
               case 51:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(54, 56);
                  break;
               case 53:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(54, 56);
                  break;
               case 56:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddTwoStates(56, 57);
                  break;
               case 58:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
                  break;
               case 59:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddTwoStates(56, 57);
                  break;
               case 63:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(61, 65);
                  break;
               case 65:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(61, 65);
                  break;
               case 68:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(66, 70);
                  break;
               case 70:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(66, 70);
                  break;
               case 73:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(75, 78);
                  break;
               case 76:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(71, 75);
                  break;
               case 78:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(71, 75);
                  break;
               case 80:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(76, 80);
                  break;
               case 82:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 83:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 73)
                     kind = 73;
                  jjCheckNAddStates(76, 80);
                  break;
               case 84:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(75, 78);
                  break;
               case 85:
                  if ((0x87fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(85);
                  break;
               case 86:
                  if ((0x78000001f8000001L & l) != 0L && kind > 77)
                     kind = 77;
                  break;
               case 92:
               case 94:
                  if (curChar == 124 && kind > 63)
                     kind = 63;
                  break;
               case 93:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 102:
                  if (curChar == 123)
                     jjCheckNAddStates(81, 84);
                  break;
               case 103:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 104;
                  break;
               case 104:
                  jjCheckNAddStates(81, 84);
                  break;
               case 105:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(81, 84);
                  break;
               case 106:
               case 108:
                  if (curChar == 125)
                     jjCheckNAdd(105);
                  break;
               case 107:
                  if (curChar == 125)
                     jjAddStates(85, 86);
                  break;
               case 109:
                  if (curChar == 125 && kind > 65)
                     kind = 65;
                  break;
               case 110:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 112:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 85:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 76)
                     kind = 76;
                  jjCheckNAdd(85);
                  break;
               case 3:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 61)
                     kind = 61;
                  break;
               case 6:
               case 7:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(16, 18);
                  break;
               case 16:
               case 17:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(19, 22);
                  break;
               case 104:
               case 105:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(81, 84);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 123 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
private final int jjMoveStringLiteralDfa0_1()
{
   return jjMoveNfa_1(1, 0);
}
private final int jjMoveNfa_1(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 122;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff0000ffffd9ffL & l) != 0L)
                  {
                     if (kind > 59)
                        kind = 59;
                     jjCheckNAdd(82);
                  }
                  else if ((0xfc00fffe00000000L & l) != 0L)
                  {
                     if (kind > 60)
                        kind = 60;
                  }
                  else if ((0x100000200L & l) != 0L)
                  {
                     if (kind > 58)
                        kind = 58;
                     jjCheckNAddStates(87, 89);
                  }
                  else if ((0x2400L & l) != 0L)
                  {
                     if (kind > 57)
                        kind = 57;
                     jjCheckNAddStates(90, 96);
                  }
                  if ((0xc00040800000000L & l) != 0L)
                  {
                     if (kind > 45)
                        kind = 45;
                     jjCheckNAddTwoStates(4, 5);
                  }
                  else if (curChar == 13)
                     jjAddStates(97, 102);
                  else if (curChar == 33)
                     jjCheckNAddTwoStates(86, 85);
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 19;
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 10;
                  if (curChar == 58)
                  {
                     if (kind > 52)
                        kind = 52;
                     jjCheckNAdd(18);
                  }
                  else if (curChar == 33)
                  {
                     if (kind > 47)
                        kind = 47;
                     jjCheckNAdd(7);
                  }
                  break;
               case 3:
                  if ((0xfffffffeffffd9ffL & l) != 0L && kind > 44)
                     kind = 44;
                  break;
               case 4:
                  if ((0xc00040800000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAddTwoStates(4, 5);
                  break;
               case 5:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(5);
                  break;
               case 6:
               case 85:
                  if (curChar != 33)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAdd(7);
                  break;
               case 8:
                  if (curChar == 45)
                     jjCheckNAdd(9);
                  break;
               case 9:
                  if (curChar != 45)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(9);
                  break;
               case 10:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 11:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 14:
               case 15:
                  jjCheckNAddStates(103, 105);
                  break;
               case 17:
                  if (curChar != 58)
                     break;
                  if (kind > 52)
                     kind = 52;
                  jjCheckNAdd(18);
                  break;
               case 18:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 52)
                     kind = 52;
                  jjCheckNAdd(18);
                  break;
               case 19:
                  if (curChar == 39 && kind > 54)
                     kind = 54;
                  break;
               case 20:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 26:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(26, 27);
                  break;
               case 27:
                  if (curChar == 58)
                     jjAddStates(106, 110);
                  break;
               case 29:
                  if ((0x3ff680000000000L & l) != 0L)
                     jjCheckNAddTwoStates(29, 27);
                  break;
               case 30:
                  if (curChar != 47)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(111, 118);
                  break;
               case 31:
                  if ((0x2fff6fd200000000L & l) != 0L)
                     jjCheckNAddStates(119, 121);
                  break;
               case 32:
                  if (curChar == 37)
                     jjCheckNAdd(33);
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(119, 121);
                  break;
               case 36:
                  if (curChar == 37)
                     jjCheckNAdd(37);
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(122, 127);
                  break;
               case 39:
                  if ((0x2bff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(122, 127);
                  break;
               case 40:
                  if (curChar == 58)
                     jjCheckNAdd(41);
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(128, 131);
                  break;
               case 42:
                  if (curChar != 47)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(132, 136);
                  break;
               case 43:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(132, 136);
                  break;
               case 44:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 45:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(132, 136);
                  break;
               case 47:
                  if (curChar != 63)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(137, 139);
                  break;
               case 48:
                  if ((0xafffefd200000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(137, 139);
                  break;
               case 49:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(137, 139);
                  break;
               case 52:
                  if (curChar != 35)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddTwoStates(53, 54);
                  break;
               case 53:
                  if ((0xafffefd200000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddTwoStates(53, 54);
                  break;
               case 54:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddTwoStates(53, 54);
                  break;
               case 57:
                  if (curChar == 37)
                     jjCheckNAddTwoStates(33, 37);
                  break;
               case 58:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 59:
                  if (curChar != 47)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(140, 143);
                  break;
               case 60:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(144, 148);
                  break;
               case 61:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(144, 148);
                  break;
               case 64:
                  if (curChar != 47)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(149, 153);
                  break;
               case 65:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(149, 153);
                  break;
               case 66:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(149, 153);
                  break;
               case 69:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(72, 75);
                  break;
               case 72:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(154, 158);
                  break;
               case 75:
                  if ((0x2bff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(154, 158);
                  break;
               case 76:
                  if (curChar != 47)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(159, 163);
                  break;
               case 77:
                  if ((0x2fff6fd200000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(159, 163);
                  break;
               case 78:
                  if (curChar == 37)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(159, 163);
                  break;
               case 81:
                  if ((0x2bff6fd200000000L & l) != 0L)
                     jjCheckNAddTwoStates(72, 75);
                  break;
               case 82:
                  if ((0x3ff0000ffffd9ffL & l) == 0L)
                     break;
                  if (kind > 59)
                     kind = 59;
                  jjCheckNAdd(82);
                  break;
               case 83:
                  if ((0xfc00fffe00000000L & l) != 0L && kind > 60)
                     kind = 60;
                  break;
               case 84:
                  if (curChar == 33)
                     jjCheckNAddTwoStates(86, 85);
                  break;
               case 86:
                  if (curChar == 33)
                     jjCheckNAdd(85);
                  break;
               case 87:
                  if (curChar == 13)
                     jjAddStates(97, 102);
                  break;
               case 88:
                  if (curChar == 10)
                     jjCheckNAdd(4);
                  break;
               case 89:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(91, 92);
                  break;
               case 93:
                  if (curChar == 10)
                     jjCheckNAddTwoStates(6, 84);
                  break;
               case 94:
                  if (curChar == 10)
                     jjCheckNAdd(105);
                  break;
               case 97:
               case 98:
                  jjCheckNAddStates(164, 167);
                  break;
               case 106:
                  if (curChar == 10)
                     jjCheckNAdd(11);
                  break;
               case 107:
                  if (curChar == 10 && kind > 57)
                     kind = 57;
                  break;
               case 108:
                  if ((0x2400L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAddStates(90, 96);
                  break;
               case 114:
               case 115:
                  jjCheckNAddStates(168, 171);
                  break;
               case 119:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAddStates(87, 89);
                  break;
               case 120:
                  if ((0x100000200L & l) != 0L)
                     jjCheckNAddTwoStates(120, 17);
                  break;
               case 121:
                  if ((0x100000200L & l) == 0L)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAdd(121);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x87fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 59)
                        kind = 59;
                     jjCheckNAdd(82);
                  }
                  else if ((0x78000001f8000001L & l) != 0L)
                  {
                     if (kind > 60)
                        kind = 60;
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(26, 27);
                  else if (curChar == 123)
                     jjCheckNAddTwoStates(104, 112);
                  else if (curChar == 124)
                  {
                     if (kind > 46)
                        kind = 46;
                  }
                  else if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 23;
                  else if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 21;
                  else if (curChar == 91)
                     jjCheckNAddStates(103, 105);
                  else if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 3;
                  if (curChar == 124)
                     jjCheckNAddTwoStates(90, 110);
                  else if (curChar == 91)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 0:
                  if (curChar == 91 && kind > 44)
                     kind = 44;
                  break;
               case 2:
                  if (curChar == 126)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if (kind > 44)
                     kind = 44;
                  break;
               case 12:
                  if (curChar == 91)
                     jjCheckNAddStates(103, 105);
                  break;
               case 13:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  jjCheckNAddStates(103, 105);
                  break;
               case 15:
                  if ((0xffffffffd7ffffffL & l) != 0L)
                     jjCheckNAddStates(103, 105);
                  break;
               case 16:
                  if (curChar == 93 && kind > 50)
                     kind = 50;
                  break;
               case 21:
                  if (curChar == 95 && kind > 54)
                     kind = 54;
                  break;
               case 22:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 23:
                  if (curChar == 92 && kind > 55)
                     kind = 55;
                  break;
               case 24:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
               case 26:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(26, 27);
                  break;
               case 28:
               case 29:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(29, 27);
                  break;
               case 31:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddStates(119, 121);
                  break;
               case 33:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddStates(119, 121);
                  break;
               case 35:
                  if (curChar != 64)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(122, 127);
                  break;
               case 37:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(122, 127);
                  break;
               case 39:
                  if ((0x47fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(122, 127);
                  break;
               case 43:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(132, 136);
                  break;
               case 45:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(132, 136);
                  break;
               case 48:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(137, 139);
                  break;
               case 50:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  break;
               case 51:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(137, 139);
                  break;
               case 53:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddTwoStates(53, 54);
                  break;
               case 55:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddTwoStates(53, 54);
                  break;
               case 60:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(144, 148);
                  break;
               case 62:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(144, 148);
                  break;
               case 65:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(149, 153);
                  break;
               case 67:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 68:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(149, 153);
                  break;
               case 70:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x7e0000007eL & l) != 0L)
                     jjCheckNAddTwoStates(72, 75);
                  break;
               case 73:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(154, 158);
                  break;
               case 75:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(154, 158);
                  break;
               case 77:
                  if ((0x47fffffe87ffffffL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(159, 163);
                  break;
               case 79:
                  if ((0x7e0000007eL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAddStates(159, 163);
                  break;
               case 81:
                  if ((0x47fffffe87fffffeL & l) != 0L)
                     jjCheckNAddTwoStates(72, 75);
                  break;
               case 82:
                  if ((0x87fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 59)
                     kind = 59;
                  jjCheckNAdd(82);
                  break;
               case 83:
                  if ((0x78000001f8000001L & l) != 0L && kind > 60)
                     kind = 60;
                  break;
               case 90:
                  if (curChar == 124 && kind > 46)
                     kind = 46;
                  break;
               case 91:
                  if (curChar == 124)
                     jjCheckNAdd(90);
                  break;
               case 92:
                  if (curChar == 124 && kind > 46)
                     kind = 46;
                  break;
               case 95:
                  if (curChar == 123)
                     jjCheckNAddStates(164, 167);
                  break;
               case 96:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 97;
                  break;
               case 97:
                  jjCheckNAddStates(164, 167);
                  break;
               case 98:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(164, 167);
                  break;
               case 99:
               case 101:
                  if (curChar == 125)
                     jjCheckNAdd(98);
                  break;
               case 100:
                  if (curChar == 125)
                     jjAddStates(172, 173);
                  break;
               case 102:
                  if (curChar == 125 && kind > 48)
                     kind = 48;
                  break;
               case 103:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 102;
                  break;
               case 104:
                  if (curChar == 123)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 105:
                  if (curChar == 123)
                     jjCheckNAdd(104);
                  break;
               case 109:
                  if (curChar == 124)
                     jjCheckNAddTwoStates(90, 110);
                  break;
               case 110:
                  if (curChar == 124 && kind > 51)
                     kind = 51;
                  break;
               case 111:
                  if (curChar == 123)
                     jjCheckNAddTwoStates(104, 112);
                  break;
               case 112:
                  if (curChar == 123)
                     jjCheckNAddStates(168, 171);
                  break;
               case 113:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 114:
                  jjCheckNAddStates(168, 171);
                  break;
               case 115:
                  if ((0xdfffffffffffffffL & l) != 0L)
                     jjCheckNAddStates(168, 171);
                  break;
               case 116:
                  if (curChar == 125)
                     jjCheckNAdd(115);
                  break;
               case 117:
                  if (curChar == 125 && kind > 53)
                     kind = 53;
                  break;
               case 118:
                  if (curChar == 125)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (int)(curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
               case 82:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 59)
                     kind = 59;
                  jjCheckNAdd(82);
                  break;
               case 3:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 44)
                     kind = 44;
                  break;
               case 14:
               case 15:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(103, 105);
                  break;
               case 97:
               case 98:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(164, 167);
                  break;
               case 114:
               case 115:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddStates(168, 171);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 122 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   121, 12, 122, 89, 93, 94, 96, 112, 117, 98, 88, 91, 95, 101, 113, 118, 
   5, 7, 8, 15, 17, 18, 20, 31, 61, 62, 72, 84, 34, 38, 42, 43, 
   45, 50, 55, 60, 35, 34, 38, 39, 42, 43, 45, 50, 55, 44, 45, 50, 
   55, 45, 46, 47, 50, 55, 51, 52, 55, 63, 64, 50, 55, 63, 64, 67, 
   50, 55, 67, 68, 69, 50, 55, 75, 78, 79, 50, 55, 79, 80, 81, 50, 
   55, 103, 105, 106, 107, 108, 110, 120, 17, 121, 4, 91, 92, 6, 105, 11, 
   84, 88, 89, 93, 94, 106, 107, 13, 15, 16, 28, 58, 59, 69, 81, 31, 
   35, 39, 40, 42, 47, 52, 57, 32, 31, 35, 36, 39, 40, 42, 47, 52, 
   41, 42, 47, 52, 42, 43, 44, 47, 52, 48, 49, 52, 60, 61, 47, 52, 
   60, 61, 64, 47, 52, 64, 65, 66, 47, 52, 72, 75, 76, 47, 52, 76, 
   77, 78, 47, 52, 96, 98, 99, 100, 113, 115, 116, 118, 101, 103, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
   "INITIAL_CONTEXT", 
};
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[123];
private final int[] jjstateSet = new int[246];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
public JspWikiScannerTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public JspWikiScannerTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 123; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 2 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   if (jjmatchedPos < 0)
   {
      if (image == null)
         t.image = "";
      else
         t.image = image.toString();
      t.beginLine = t.endLine = input_stream.getBeginLine();
      t.beginColumn = t.endColumn = input_stream.getBeginColumn();
   }
   else
   {
      String im = jjstrLiteralImages[jjmatchedKind];
      t.image = (im == null) ? input_stream.GetImage() : im;
      t.beginLine = input_stream.getBeginLine();
      t.beginColumn = input_stream.getBeginColumn();
      t.endLine = input_stream.getEndLine();
      t.endColumn = input_stream.getEndColumn();
   }
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   switch(curLexState)
   {
     case 0:
       jjmatchedKind = 0x7fffffff;
       jjmatchedPos = 0;
       curPos = jjMoveStringLiteralDfa0_0();
       break;
     case 1:
       jjmatchedKind = 57;
       jjmatchedPos = -1;
       curPos = 0;
       curPos = jjMoveStringLiteralDfa0_1();
       break;
   }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default : 
         break;
   }
}
}
